project:
  type: website
website:
  title: "Mark Vanderstay"
  description: "Mark Vanderstay's Personal Blog"
  site-url: markvanderstay.com
  navbar:
    right:
      - about.qmd
      - icon: linkedin
        href: https://linkedin.com/in/mark-vanderstay
      - icon: twitter
        href: https://twitter.com/m_vanders
      - icon: rss
        href: index.xml
  open-graph: true
  google-analytics: "G-CELTXHBN60"
  twitter-card: 
    creator: "@m_vanders"
    site: "@m_vanders"
format:
  html:
    theme: 
      light: lux
    css: styles.css
    code-overflow: scroll
    code-block-bg: true
    code-block-border-left: "#1a1a1a"
editor: visual