---
title: "About Me"
image: ""
about:
  template: jolla
  links:
    - icon: twitter
      text: Twitter
      href: https://twitter.com/m_vanders
    - icon: linkedin
      text: LinkedIn
      href: https://linkedin.com/in/mark-vanderstay
---

## Mark Vanderstay

I'm a data science professional with a unique blend of skills and experience. With a background in biostatistics, psychology, and ecommerce, I have a well-rounded perspective on data analysis and its application in real-world settings. I believe in leveraging my skills to create impact for my clients and am passionate about helping businesses make data-driven decisions.

Are you looking to take your data strategy to the next level? [Contact me](mailto:hello@markvanderstay.com) for a chat! I offer a free consultation to discuss your needs and see how I can help.

## Education & Experience

MSc in Psychology Research Methods and many years experience in biostatistics.

Klaviyo Partner

MailChimp Certified

GA4 Certified

SAS, R, Python, C#, Ruby

## Contact

You can find me on [Twitter](https://twitter.com/m_vanders) and [LinkedIn](https://linkedin.com/in/mark-vanderstay).

[Send me an email](mailto:hello@markvanderstay.com).

Check out more R posts on [R-Bloggers.com](https://www.r-bloggers.com/)
